async function updateLeaderboard() {
    try {
        // Fetch the file generated by GitHub Actions
        const response = await fetch('data.json');
        const ranks = await response.json();

        // Find all player cards
        const cards = document.querySelectorAll('.card--profile');
        
        cards.forEach(card => {
            const nameElement = card.querySelector('.card-title');
            const metaElement = card.querySelector('.card-meta');
            
            if (nameElement && metaElement) {
                const playerName = nameElement.innerText.trim().toUpperCase();
                if (ranks[playerName]) {
                    metaElement.innerText = ranks[playerName];
                }
            }
        });
    } catch (e) {
        console.log("Ranks not yet loaded or file missing.");
    }
}

// Run on page load
document.addEventListener('DOMContentLoaded', updateLeaderboard);
