async function loadData() {
    try {
        // 1. Fetch the data generated by your GitHub Action
        const res = await fetch('./data.json');
        if (!res.ok) throw new Error("Data file not found");
        const data = await res.json();

        const teams = ["prime", "spark", "ember", "nova", "abyss", "night", "freezer"];
        const roles = ["top", "jgl", "mid", "bot", "sup", "coach"];

        teams.forEach(team => {
            roles.forEach(role => {
                const key = `${team}_${role}`;
                const stats = data[key];

                // Target UI Elements
                const nameEl = document.getElementById(`${key}_name`);
                const rankEl = document.getElementById(`${key}_rank`);
                const wlEl   = document.getElementById(`${key}_wl`);
                const iconEl = document.getElementById(`${key}_icon`);
                const lvlEl  = document.getElementById(`${key}_level`);

                if (stats) {
                    // Update Text Data
                    if (nameEl) nameEl.innerText = stats.name;
                    if (rankEl) rankEl.innerText = stats.rank;
                    if (wlEl)   wlEl.innerText   = `W/L: ${stats.wl}`;
                    if (lvlEl)  lvlEl.innerText  = stats.level;

                    // Update Riot Icon with "Broken Image" fix
                    if (iconEl) {
                        // PRIMING THE ERROR HANDLER: 
                        // We set this before the .src to catch immediate load failures.
                        iconEl.onerror = function() {
                            this.src = 'assets/profile/placeholder.png';
                            this.onerror = null; // Prevents infinite loops if placeholder is missing
                        };
                        
                        iconEl.src = stats.icon;
                        iconEl.style.display = "block";
                    }
                } else {
                    // Handle "OPEN SPOT" / Missing Data Logic
                    if (nameEl) nameEl.innerText = "OPEN SPOT";
                    if (rankEl) rankEl.innerText = "RECRUITING";
                    if (wlEl)   wlEl.innerHTML   = "&nbsp;";
                    if (lvlEl)  lvlEl.innerText  = "0";
                    
                    if (iconEl) {
                        // Option: Set to placeholder or hide. 
                        // Since we want a clean HUD, hiding is usually best for open spots.
                        iconEl.style.display = "none"; 
                        iconEl.src = "";
                    }
                }
            });
        });
        console.log("HUD Data Sync: Successful");
    } catch (e) {
        console.error("Tactical HUD Error: Could not load data.json", e);
    }
}

// Initialize HUD on Page Load
document.addEventListener('DOMContentLoaded', loadData);