[
  { "name": "UIC SPEEDY", "puuid": "0Mb0Fq-ZW6AR5GujHCw_ZU6b27tgqVD4BBx7Ls_SWuMc7UV2CmoYzaRteyU3kXhZpTNrdkyBviPloQ" },
  { "name": "UIC NIKI", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC SHANYCRANE", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC GIANI", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC BAGUETTO", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC SKANPY", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC LENNO", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC ON1R", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC FLARE", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC KUGELBLITZ", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC SHEDEREN", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC MICHELINMANN", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC DONTMETHWITHME", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC ENVY", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC ADEDIER", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC RUBIX QUBE", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC APATHY", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC SIMPLY", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC EXCELLENT C", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC DANY", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC KEYGASZA", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC GOKU", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC N1GHTM4REX", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC EIGEEEN", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC RECORD", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC PROSTARII", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC CEDO", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC SHEKAR", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC KALTERKLAUS", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC FROZENHANDS", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC AUTUMNLEAF", "puuid": "PASTE_PUUID_HERE" },
  { "name": "UIC LOONZ", "puuid": "PASTE_PUUID_HERE" }
]
